sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t chloe101/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true chloe101/react-test npm run test
after_success:
  - docker build -t chloe101/multi-client ./client
  - docker build -t chloe101/multi-nginx ./nginx
  - docker build -t chloe101/multi-server ./server
  - docker build -t chloe101/multi-worker ./worker